name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  windows:
    name: windows-msvc
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - uses: ilammy/msvc-dev-cmd@v1.10.0
    - name: compile
      run: cl BS_thread_pool_test.cpp /EHsc /O2 /DNDEBUG /std:c++17

    - name: run
      run: ./BS_thread_pool_test.exe

  ubuntu:
    name: ubuntu-${{matrix.compiler}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
    steps:
    - uses: actions/checkout@v3

    - name: compile
      run: ${{matrix.compiler}} -std=c++17 BS_thread_pool_test.cpp -o BS_thread_pool_test -lpthread

    - name: run
      run: ./BS_thread_pool_test
